### ISSUE TITLE
Input lag compared to other cores

### ISSUE THREAD

**Issue by Adam7288** [libretro/bsnes-mercury#11]
Independent of retroarch, gpu, os settings etc, apples-to-apples comparison to other cores for different systems, this core produces massive input lag.

Worth nothing: all SNES cores produce much higher input lag than other cores, including systems much newer such as psx and n64. Snes9x based cores produce similar input lag.

Racking my brain, what is unique about the SNES architecture, is it the custom Sony sound chip (SPC700)? Or possibly the poorly documented GPU?

In any case, SNES gaming requires responsive input to be satisfying and accurate. I am posting this issue to the Bsnes mercury Github because it seems this is the most actively developed core. Interested in any thoughts on this matter.

**Comment by fr500** [comment]
Have you actually measured?

**Comment by Adam7288** [comment]
Besides my subjective experience with SNES real hardware and various emulation configurations, as well as confirmation with other anecdotal evidence - http://libretro.com/forums/showthread.php?t=3603

I have taken a slow motion video with iphone to demonstrate the issue. I am going to save you the trouble and tell you I have spent hours eliminating all possible causes of the lag, from the obvious to the not-so-obvious.

http://tinypic.com/player.php?v=eah4rc%3E&s=8#.Vg4S4_lVhBc

**Comment by Alcaro** [comment]
Fixed by #18
