### ISSUE TITLE
HLE for Most Chips Crashes RetroArch

### ISSUE THREAD

**Issue by bleakassassin** [libretro/bsnes-mercury#14]
Any game that I try to play that uses just about any of the chips that require data and program ROMs for LLE chip causes major issues in RetroArch. Games that use the DSP-1 chips work until you get to a point in the game that uses them. Games that use the other chips requiring the copyrighted files will crash RetroArch immediately. All games with the affected chips work correctly if you use the data and program ROMs and LLE emulation.

Some other chips that don't have separate files are also affected adversely. I'll keep a tally on those in the recap.

Oddly enough, F1 ROC II: Race of Champions (which uses the ST010 chip) plays just fine via HLE, even though the two Hayazashi Nidan Morita Shogi games (ST011 and ST018 chips) don't.

The auto-build from 2015-12-17 was the last build where games with these chips didn't result in a crash. Something from the bsnes/higan v096 update must have caused this to break.

To reiterate, games using these chips no longer work when using HLE:
*DSP-1
*DSP-1A
*DSP-1B
*DSP-2
*DSP-3
*DSP-4
*ST011
*ST018
*CX4
*S-DD1
*SPC7110

I'd try to spend more time trying to figure this out, but... holidays.

**Comment by Alcaro** [comment]
bsnes has to be the most hateful program I've ever seen. Those BMLs lose all the type and typo checking, I can't even figure out what it's doing.

I'll just revert master to 094 and dump 096 on a branch, this shit isn't worth it.
