### ISSUE TITLE
Game Genie cheat somehow broke cores

### ISSUE THREAD

**Issue by GeneralFailer** [libretro/bsnes-mercury#29]
Super Ghouls 'n Ghosts crashes on at least the first cheat with `terminate called after throwing an instance of 'nall::vector<CheatList>::exception_out_of_bounds'` on normal bsnes core similarly to #25. Since I've attempted to load it with bsnes-mercury all its cores started crashing with a segmentation fault when loading any roms for some reason.

build a0a8079
OS: Arch Linux w/ KMS

**Comment by GeneralFailer** [comment]
Any suggestions on how to fix it at least?  Updating cores doesn't work. The message is just "Segmentation fault (core dumped)."

**Comment by hizzlekizzle** [comment]
the first thing to try would be a clean config (including clean core options) to see if that gets it working again.

**Comment by GeneralFailer** [comment]
It was probablyunrelated.
