### ISSUE TITLE
Star Ocean - Corrupted graphics with the Tractor Beam spell

### ISSUE THREAD

**Issue by orbea** [libretro/bsnes-mercury#34]
## Description

In the game Star Ocean with either the nointro Japanese rom or the dejap translations whenever the spell "Tractor Beam" by the character Joshua is used at least some of the character and enemies sprites will be corrupted during the spell animation.

This issue is present in both bsnes-mercury and bsnes-libretro with all three of the accuracy profiles, but it is not present in snes9x-libretro. I am reporting it here as I was using bsnes-mercury when I ran into it.

Here is a srm file that should work with any of the snes libretro emulators and any version of the Star Ocean rom.
http://ks392457.kimsufi.com/orbea/stuff/games/Star%20Ocean%20(Japan).srm

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/bsnes/Star%20Ocean%20(Japan)-170305-115912.png)

### Expected behavior

The graphics should not be corrupted when the "Tractor Beam" spell is used.

### Actual behavior

When the "Tractor Beam" spell is used the graphics are corrupted.

### Steps to reproduce the bug

1. Load bsnes with the provided srm file.
2. Load a saved game and run around until a battle starts.
3. In the battle press `b` and switch to Joshua (Winged character), then press `Y` to open the character menu and select the last spell at the bottom right (Tractor Beam in the dejap translation).
4. After the spell successfully initiates the graphics should be corrupted on at least some of the characters or enemies.

### Bisect Results

I tested as far back as commit 059235c (2016.01.26) and it still occurred, if it was a regression it was not recent.

### Version/Commit

`bsnes-libretro-2017.02.04_026fc306_libretro-x86_64-1_git`
`bsnes-mercury-2017.02.04_9061b90_master-x86_64-1_git`
`snes9x-libretro-2017.01.26_2d579c6_master-x86_64-1_git`
`RetroArch-2017.02.27_a6420ae96_master-x86_64-1_git`

### Environment information

- OS: `Slackware64-current`
- Compiler: `gcc-5.4.0`

**Comment by orbea** [comment]
I've tested further, this doesn't occur with snes9x-libretro, snex9x-2010 or snes9x-2005 while snes9x-2002 is too broken to test. It does occur with bsnes-libretro, bsnes-mercury, beetle-bsnes and mednafen upstream. I have not tested higan however.

**Comment by hizzlekizzle** [comment]
Looks like it happens in higan standalone, too:
http://i.imgur.com/g3R6eLu.png

**Comment by orbea** [comment]
@hizzlekizzle What version of higan standalone did you try?

I can't reproduce it in higan-101.

**Comment by orbea** [comment]
I can reproduce it with higan-094, so its been fixed between versions 094 and 101, I will have to bisect it to see when it was fixed, but given that the higan build system has changed for no real benefit between those two versions bisecting is going to be a pain...

**Comment by orbea** [comment]
Given the range of commits, my guess is the Star Ocean commit was fixed in one of these.

https://gitlab.com/higan/higan/commit/4b29f4bad7dacf3adad48f718876d935a355491e
https://gitlab.com/higan/higan/commit/680d16561e8584cbe0b5b0296db8a73016333cb0
https://gitlab.com/higan/higan/commit/1929ad47d2030dce1014a350469243d1197fe53e
https://gitlab.com/higan/higan/commit/095529547576de0267d62685d60043758dd91aa4

**Comment by orbea** [comment]
I was able to confirm it was fixed in the higan commit `095529547576de0267d62685d60043758dd91aa4` by compiling it where it was fixed and its parent commit which still had the issue with the following patch.
```
diff --git a/higan/fc/interface/interface.cpp b/higan/fc/interface/interface.cpp
index 4e6193e..b77615c 100644
--- a/higan/fc/interface/interface.cpp
+++ b/higan/fc/interface/interface.cpp
@@ -98,14 +97,14 @@ auto Interface::videoColor(uint32 n) -> uint64 {
     v *= brightness / 12.0;
 
     y += v;
-    i += v * std::cos((3.141592653 / 6.0) * (p + hue));
-    q += v * std::sin((3.141592653 / 6.0) * (p + hue));
+    i += v * cos((3.141592653 / 6.0) * (p + hue));
+    q += v * sin((3.141592653 / 6.0) * (p + hue));
   }
 
   i *= saturation;
   q *= saturation;
 
-  auto gammaAdjust = [=](double f) { return f < 0.0 ? 0.0 : std::pow(f, 2.2 / gamma); };
+  auto gammaAdjust = [=](double f) { return f < 0.0 ? 0.0 : pow(f, 2.2 / gamma); };
   uint64 r = uclamp<16>(65535.0 * gammaAdjust(y +  0.946882 * i +  0.623557 * q));
   uint64 g = uclamp<16>(65535.0 * gammaAdjust(y + -0.274788 * i + -0.635691 * q));
   uint64 b = uclamp<16>(65535.0 * gammaAdjust(y + -1.108545 * i +  1.709007 * q));

```
https://gitlab.com/higan/higan/commit/095529547576de0267d62685d60043758dd91aa4

**Comment by orbea** [comment]
@Alcaro When you have a chance can you try backporting the SDD1 fixes from the above commit? Converting the c++ conventions in higan for the cleaner code in libretro in is beyond me...

**Comment by hizzlekizzle** [comment]
How does that patch affect anything SDD1-related? It looks like a change to fc (i.e. famicom) interface...?

**Comment by orbea** [comment]
That patch doesn't affect SDD1, it fixes the fc compile which prevented me from building sfc since I could not figure out how to only build sfc with higan...

**Comment by Alcaro** [comment]
I'm no longer part of this project.

**Comment by orbea** [comment]
Well, that is sad to hear. :( I appreciate all that you have done for libretro and it would be unfortunate to lose you, but I do understand your frustrations.
